# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.hostname = "laravel"
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.synced_folder "../www", "/var/www"
  config.vm.provision "ansible", run: "always" do |ansible|
    ansible.sudo = true
    ansible.groups = {"web" => ['laravel']}
    ansible.playbook = "../provision/vagrant.yml"
  end
end
