# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.hostname = "laravel.lan"
  # https://groups.google.com/forum/m/#!topic/vagrant-up/yNhWV42pcgk
  config.vm.network "public_network", :use_dhcp_assigned_default_route => true
  config.vm.synced_folder "../www", "/var/www"
  config.vm.provision "ansible", run: "always" do |ansible|
    ansible.sudo = true
    ansible.groups = {"web" => ['laravel']}
    ansible.playbook = "../provision/vagrant.yml"
  end
end
